Hanaro-trip-together-bank/front

src/components/common/Modals/Modal.tsx
src/components/common/Navigation/NavigationLink.tsx
src/components/common/Navigation/NavigationStack.tsx
src/components/common/TopBars/NavigationBar.tsx
src/contexts/useNavigation.tsx
src/index.css
src/types/Route.d.ts

<br/>
<br/>
```
Route 타입: {
backgroundColor?: string;
page: ReactNode;
}
```
<br/>
* 약간의 css 수정 
<br/>
<br/>

feat: 네비게이션 타입 변경 및 css 약간 수정 (#1) 

---

src/components/common/Arrow.tsx
src/components/common/Button.tsx
src/components/common/Navigation/NavigationLink.tsx
src/components/common/Select.tsx
src/components/common/Select2.tsx
src/components/common/TopBars/NavigationBar.tsx
src/contexts/useNavigation.tsx
src/hooks/useToggle.ts
src/index.css
src/pages/DemoPage.tsx
src/pages/Main/LoginPage.tsx
src/pages/Main/MainPage.tsx
src/pages/MoimService/Dues/MoimDepositPage.tsx
src/pages/MoimService/Dues/MoimDuesMainPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/pages/MoimService/SignUp/MoimServiceSignUpPage.tsx
src/stories/common/Button.stories.ts
src/utils/currentTime.ts
src/utils/printMoney.ts

<br/>
* useToggle
```
const [value, toggleValue] = useToggle();
```
* 페이지들
<br/>

feat: 하나원큐 기본 페이지 작성 (1) #6

---

src/components/common/Button.tsx
src/components/common/Check.tsx
src/components/common/Modals/Modal.tsx
src/hooks/useKeypadMappedNumber.ts
src/hooks/usePassword.ts
src/pages/Main/LoginPage.tsx
src/pages/MoimService/Dues/MoimDepositPage.tsx
src/pages/MoimService/Dues/MoimDuesMainPage.tsx
src/pages/MoimService/Dues/MoimDuesSetPage.tsx
src/utils/printMoney.ts

* usePassword, useKeypadMappedNumber 훅
```
const { amount, append, remove, add, clear } = useKeypadMappedNumber();
const { password, append, remove } = usePassword();
```
* Modal 옵션 추가
```
hideBackDrop?: boolean
```
* 체크서클
<br/>
<br/>
* 회비 설정 페이지
<br/>
<br/>
* 입금 페이지
<br/>
<br/>
<br/>
<br/>

feat: 하나원큐 기본 페이지 작성 (2) #6

---

src/types/City.d.ts
src/types/Trip.d.ts
src/types/TripPlace.d.ts
src/types/TripReply.d.ts

<br/>
<br/>
<br/>
- TripPlace 관련 타입 정의
- TripReply 관련 타입 정의
- Trip 관련 타입 정의

feat: 여행 장소/장소 댓글/여행 조회 타입 정의 (#12)

---

src/types/City.d.ts
src/types/Trip.d.ts
src/types/TripPlace.d.ts
src/types/TripReply.d.ts

fix: 타입 카멜케이스로 변경

---

src/types/member/MemberResponseDto.d.ts

feat: Member DTO 타입 정의 추가

---

src/types/Category.d.ts
src/types/Continent.d.ts
src/types/Country.d.ts
src/types/Place.d.ts
src/types/Trip.d.ts

feat: Trip DTO 타입 정의 추가

---

src/components/common/Modals/Loading.tsx
src/components/common/Navigation/NavigationStack.tsx
src/hooks/useFetch.ts
src/index.css
src/pages/Main/MainPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/types/account/AccountResponseDto.d.ts
src/types/team/TeamRequestDto.d.ts
src/utils/urlFactory.ts

<br/>
<br/>
<br/>
- 내 모임 조회 api 연결
- css 변경
<br/>

feat: 내 모임 조회 api 연결

---

src/pages/MoimService/MoimServiceMainPage.tsx
src/types/account/AccountResponseDto.d.ts

feat: 총무 표시

---

src/pages/MoimService/MoimServiceMainPage.tsx
src/pages/MoimService/SignUp/MoimServiceSignUpPage.tsx
src/types/account/AccountRequestDto.d.ts
src/utils/formatAccNo.ts
src/utils/urlFactory.ts

<br/>
<br/>
+ formatAccNo
+ 모임서비스 가입 서버연동(계좌조회, 모임생성요청)
<br/>
<br/>

feature: 모임서비스 가입 페이지 (#31)

---

src/hooks/useFetch.ts
src/pages/MoimService/Management/MoimManagementPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/pages/MoimService/SignUp/MoimServiceSignUpPage.tsx
src/types/team/TeamRequestDto.d.ts
src/utils/urlFactory.ts

<br/>
<br/>
* 모임 관리 페이지 연결, 알림 토글 기능
* useFetch → refetch 
* 기타 버그 수정 
<br/>

feat: 모임 관리 페이지 + 가입페이지 오류 수정 (#31,#34)

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx
src/types/team/TeamRequestDto.d.ts

feat: 모임원 관리 페이지 버튼 API 연결

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx

fix: 모임원 관리 async 삭제

---

src/pages/MoimService/Dues/MoimDuesMainPage.tsx
src/pages/MoimService/Dues/MoimDuesSetPage.tsx
src/types/due/Due.d.ts
src/utils/urlFactory.ts

feat: 회비 규칙 등록

---

src/components/common/Check.tsx
src/pages/MoimService/Dues/MoimDuesMainPage.tsx
src/pages/MoimService/Dues/MoimDuesRequestPage.tsx
src/types/Dues.d.ts
src/utils/urlFactory.ts

<br/>
<br/>
<br/>
- 회비 요청api연결
<br/>

feat: 회비 요청api연결 (#38)

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx

fix: 모임원 관리 페이지 refetch 적용

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx

feat: 모임원 관리- 초대링크 생성 및 복사 추가

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx

fix: 모임원 관리- 초대링크 localhost를 현재 URL로 치환

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx
src/pages/MoimService/MoimDetailPage.tsx

- [] 리팩토링 (기능적 변경 없음, API 변경 없음)
<br/>
<br/>
<br/>
<br/>

fix: 모임원 관리- teamIdx Props 연결

---

src/pages/MoimService/Dues/MoimDuesMainPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx

<br/>
<br/>
<br/>
- 모임 이름 누락 추가
<br/>

fix: 모임 이름 누락 추가

---

src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/utils/urlFactory.ts

feat: 모임서비스 상세 데이터 출력

---

src/pages/MoimService/Dues/MoimDuesRequestPage.tsx
src/utils/urlFactory.ts

<br/>
<br/>
<br/>
- api url 변경
<br/>

fix: api url 변경

---

src/pages/MoimService/MoimDetailPage.tsx
src/utils/urlFactory.ts

<br/>
<br/>
<br/>
- 공지 등록, 수정 api 연결, input 레이아웃 살짝 수정
<br/>

feat: 공지 등록, 수정 api 연결

---

src/pages/MoimService/Dues/MoimDepositPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/types/account/AccountResponseDto.d.ts

feat: 입금 페이지 데이터 출력

---

src/pages/MoimService/Dues/MoimDepositPage.tsx

fix: 입금 페이지- 동일계좌 이체불가 기능 추가

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/pages/MoimService/Trips/MoimTripDetailPage.tsx
src/utils/colorPack.ts

feat: 모임원 권한 별 예외 처리

---

src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/Trips/MoimTripsMainPage.tsx
src/types/team/TeamRequestDto.d.ts
src/types/team/TeamResponseDto.d.ts
src/types/trip/TripResponseDto.d.ts
src/utils/urlFactory.ts

feat: 여행 북마크 기능 연결

---

src/pages/MoimService/MoimDetailPage.tsx
src/pages/MoimService/MoimServiceMainPage.tsx
src/types/account/AccountResponseDto.d.ts

feat: 모임 메인-선호여행 연결

---

public/firebase-messaging-sw.js

- [x ] 버그 수정
<br/>
<br/>
- firebase-messaging-sw.js 수정
- public에서는 import.meta 안먹혀서 수정했어요. 저 정보는 노출되어도 괜찮다고 합니다.
<br/>
<br/>

refactor: firebase-messaging-sw.js 수정 #65

---

src/pages/MoimService/MoimDetailPage.tsx

fix: main에서 prefer-trip null일 경우 무한로딩 수정

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx

fix: 총무 변경 완료후 자동으로 토글창 닫히도록 수정

---

src/pages/MoimService/Members/MoimMembersMainPage.tsx
src/pages/MoimService/MoimDetailPage.tsx

fix: 모임원 관리- 모임나가기 기능 수정

---

src/pages/MoimService/Trips/MoimTripsMainPage.tsx

<br/>
즐겨찾기한 여행도 삭제 가능했음 → 삭제이상 발생
<br/>
<br/>

fix: 즐겨찾기된 여행은 삭제 못하도록

---

src/pages/MoimService/Dues/MoimDepositPage.tsx

fix: 키패드/input 겹치는 오류 해결

---

src/App.tsx
src/components/common/Alarm.tsx
src/firebaseConfig.ts
src/pages/Main/LoginPage.tsx
src/pages/Main/MainPage.tsx

- [x ] 버그 수정
- [ x] 기능 추가
<br/>
<br/>
<br/>
fcm토큰 발급까지 시간이 좀 걸려서 loading완료 되었습니다까지 기다렸다가 로그인 해주세요.
<br/>

refactor: 푸시알림 클릭시 닫기

---

src/pages/MoimService/Dues/MoimDepositPage.tsx
src/pages/MoimService/MoimDetailPage.tsx

fix: 입금 완료 후 페이지 이동시 refetch 되도록 수정

---

src/pages/MoimService/Dues/MoimDepositPage.tsx

fix: 입금시 드롭바 닫히게/동일계좌 선택 안되게

---

src/pages/MoimService/MoimDetailPage.tsx
src/types/team/TeamResponseDto.d.ts

fix: 팀원수 연결

---

src/pages/CreateTripPage.tsx
src/pages/MoimService/ExchangeRate/ExchangeRateDonePage.tsx
src/pages/MoimService/ExchangeRate/ExchangeRateMainPage.tsx
src/pages/MoimService/ExchangeRate/ExchangeRateSearchPage.tsx
src/pages/MoimService/ExchangeRate/ExchangeRateSetPage.tsx
src/pages/MoimService/MoimDetailPage.tsx
src/types/ExchangeRate.d.ts
src/types/ExchangeReate.d.ts
src/types/exchangeRate/ExchangeRate.d.ts
src/utils/urlFactory.ts

feat: ExchangeRate process done
